### ISSUE TITLE
BFX UI: Order accumulate/distribute

### ISSUE THREAD

**Issue by gazouuu** [bitfinexcom/bfx-hf-ui#139]
AMOUNT DISTORTION %
INTERVAL DISTORTION %
In the BFX UI (not the HF UI), if you input 20 it executes a distortion of 2000% and not 20%.

**Comment by drazenbencevic** [comment]
The minimum order and maximum order must be added here. And the distortion is done between the minimum and maximum orders. For example, if I put a buy slice xrp 30 (30 is the minimum order that can be placed otherwise it does not accept it, and the distortion reduces that amount. It means that this strategy will not be executed.

**Comment by ivanori1** [comment]
@drazenbencevic  and @gazouuu  I will need more explanation here, what you are suggesting to be improved ?
