### ISSUE TITLE
Order cancels on server close

### ISSUE THREAD

**Issue by lianopbs** [bitfinexcom/bfx-hf-ui#25]
Every order is cancelled upon server close or losing internet connection, and I am looking into disabling this behavior.
It would be fine if only algo-type orders would be cancelled as I can't have my long term limit orders deleted everytime.

Any hint  on where this behavior  is coded ? , I just can't find it

**Comment by JacobPlaster** [comment]
Hey @lianopbs, the feature that you are talking about is called a "deadman switch". When we connect the websocket to the bitfinex API we submit a flag that tells bitfinex to kill all orders if that websocket connection is closed.

In this case, this behaviour is located in the `bfx-hf-algo` service which is create in the background of the UI via the `bfx-hf-server` and you can see the logic here: https://github.com/bitfinexcom/bfx-hf-algo/blob/ef93d5a323d75a66bbffc6cc4df98216ae43b574/lib/ao_host.js#L59.
In order to disable this you may want to fork your own hf server and pass in the parameter to disable it.

**Comment by lianopbs** [comment]
got it, thanks. I wasn't expecting this to be located on websocket opening functions haha
