### ISSUE TITLE
react-stockcharts integration

### ISSUE THREAD

**Issue by tculig** [bitfinexcom/bfx-hf-ui#252]
In the source code there are many files directly referencing the react-stockcharts library. Some can be found under src>components>Chart>helpers. I'm trying to get them to work (render_exchange_indicators being my entry point), but can't figure out what the three in variables should be exactly { indicators, indicatorData, onOpenSettings }. I can track these variables to the Strategy Editor files, but even there it is not at all clear what these objects should look like. 

Could you offer some help?

Thanks in advanced!

**Comment by robertkowalski** [comment]
Dear @tculig, thanks for your question.

We recently removed most of the charts code in order to switch to trading view charts. I went back to 84807bcec05c8c23964de69d8c54e66744b56d39 in order to see if there is some usage of the described helper method, but no luck.

I found this code example which might be helpful: https://github.com/bitfinexcom/bfx-hf-chart/blob/master/src/Demo.js


Hope this helps a bit!

**Comment by tculig** [comment]
Hi @robertkowalski , 

Thank you for the reply. 
It wasn't too difficult to rewrite some of the missing and/or obsolete code. The problem with trading view is that its completely closed off (iframe with cross origin canvas), so I wasn't able to tinker with it at all. 

Thanks again!

Tihomir
