### ISSUE TITLE
Question: Where is the native BFX chart?

### ISSUE THREAD

**Issue by xf3rno** [bitfinexcom/bfx-hf-ui#255]
Does the TradingView public widget now support rendering positions & open orders? Iirc only `bfx-hf-chart` can do it, as the TV chart necessary cannot be hosted publically/bundled.

I've not had time to look in detail, so disregard if invalid & fixed.

**Comment by robertkowalski** [comment]
Dear cris,

nice to hear from you. We decided to remove bfx-hf-chart and switch to one chart provider in order to keep the codebase clean and simple.

Afaik TV does support custom indicators, we have not implemented it yet in HF.

Take a look at https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/?feature=technical-analysis-charts
