### ISSUE TITLE
MacOS: The application “The Honey Framework” can’t be opened.

### ISSUE THREAD

**Issue by Doweig** [bitfinexcom/bfx-hf-ui#71]
I can't execute the binary on Mac OS. Get the error `The application “The Honey Framework” can’t be opened.`

MacOS version: 10.15.2
The honey version: v3.0.3 (from github release zip) https://github.com/bitfinexcom/bfx-hf-ui/releases

**Comment by jj1980a** [comment]
I am having the same issue. A lot of applications are not run running well on Catalina, I guess that's where the problem is coming from...

**Comment by JacobPlaster** [comment]
Hi @Doweig  and @jj1980a, thanks for raising the issue. We are actually aware of this, the problem is that post High sierra mac have changed the way that their unzipping tool works which means that our builds (from our secure linux build server) are broken. In order to solve this issue, the electron app needs to be built on a mac system, which we do not have available in our datacenter.

To solve this, you can simply build the application yourselves by following the steps in the readme:
```
npm install
npm run build
npm run dist-mac
```

**Comment by ivanori1** [comment]
@Doweig  and @jj1980a  could you open HF on Mac OS now?

**Comment by ivanori1** [comment]
could not reproduce
