### ISSUE TITLE
[bug] The new Algo.Orders panel shows AO that are not running (+bad count)

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#806]
3.31.3 Stable  (development mode, live, no sandbox)

a) launch successfully 'sell' P-P with 40 slices
b) fail to launch 'buy' P-P with 30 slices - insufficient balance (500 XRP each)
c) launch successfully 'buy' P-P with 30 slices at half value (250 XRP each) 

Problem: 
the B) AO which correctly did not start:
+ is displayed in the Algo.Orders modal (shouldn't be)
+ increases the AO count in the Tradidig State Panel (wrongly)
+ cannot be killed (which is correct because it ain't running)

**Comment by pointops** [comment]
![image](https://user-images.githubusercontent.com/80652610/221646196-ca5f3d98-e5c8-40db-9545-cd8805d22599.png)

**Comment by pointops** [comment]
![image](https://user-images.githubusercontent.com/80652610/221646473-f1c02369-c370-4af6-9aef-6c5e1021dd29.png)

**Comment by pointops** [comment]
Request:

The new Algo.Orders panel should implement a validity check for AOs being displayed, the same as the previous version did. 

Apparently, this will also fix the counter in Trading State Panel which is siphoned off the Algo.Orders listed AOs. (a very strange choice, btw ?)

**Comment by pm-bfx** [comment]
Can't reproduce immediately, definitely shouldn't be there if it wasn't running. Nevertheless, it's under review... could be a signal of a more insidious issue.

**Comment by dmytroshch** [comment]
@pointops if you restart an app, does this AO appear in Resume modal?

**Comment by pointops** [comment]
Nope, it did not. Very good call. 

But tested only once. Probably I need to wait until the second week of March (31.4) for more controlled research.

**Comment by Blaumaus** [comment]
I tried to reproduce this issue but failed.

1. Submitting sell P/P AO with 40 slices: success.
<img width="1440" alt="Screenshot 2023-03-23 at 11 06 08" src="https://user-images.githubusercontent.com/35810911/227186530-89800230-3cb8-41e1-bf9e-9d37239bee5b.png">

2. Submitting buy P/P AO with 20 slices: failure due to not enough balance.
<img width="1440" alt="Screenshot 2023-03-23 at 11 07 44" src="https://user-images.githubusercontent.com/35810911/227186687-d4bd0028-96b2-4869-b3a0-0a54cde5070b.png">

3. Submitting buy P/P AO with 20 slices with lower amount of money: success.
<img width="1440" alt="Screenshot 2023-03-23 at 11 08 23" src="https://user-images.githubusercontent.com/35810911/227186868-3b9745d5-3eeb-4d1d-838b-41bd80d29676.png">

Created orders details:
<img width="1100" alt="Screenshot 2023-03-23 at 11 08 37" src="https://user-images.githubusercontent.com/35810911/227187022-d2a4c085-3ee1-4484-b021-e20693b4b594.png">
<img width="1119" alt="Screenshot 2023-03-23 at 11 08 31" src="https://user-images.githubusercontent.com/35810911/227187026-ae2fe468-dcd2-4062-a0f5-661fc381e68a.png">


In all of the requests the frontend part sent the exact data user input into the order form and rendered the orders backend sent to it correctly, the backend side also seems to work properly by either creating the order or throwing an error.


@pointops did I try to reproduce the error correctly or should I change something in here?

**Comment by Blaumaus** [comment]
Just noticed that on the screenshots I tried 20 slices instead of 30 as described above, bu I tested 30 slices as well - still not able to reproduce.

**Comment by pointops** [comment]
Hi. Your sequence seems the same as mine. 

Unintentionally I missed this ticket during my review 2 days ago. Please stand-by for me to try and reproduce it - on 3.31.4.

From what you post, it is no longer happening.
